### ISSUE TITLE
org.opentest4j.AssertionFailedError contains expected/actual fields but they are not set

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit-framework#182] opened 2016-03-10 12:10 UTC
I could found the only usage org.junit.gen5.api.Assertions#fail(java.lang.String) where the message is already formatted and no expected/actual is present

**Comment by jlink** [comment] 2016-03-10 13:44
I think it's a duplicate of #138

**Comment by marcphilipp** [comment] 2016-03-10 13:45
Yes, I think so, too.

**Closed by marcphilipp** 2016-03-10 13:45 UTC

**Comment by akozlova** [comment] 2016-03-10 13:46
Sorry, missed that.

**Comment by marcphilipp** [comment] 2016-03-10 13:58
No problem at all. :-)
